name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: coverage
      if: matrix.node == '12.x'
      run: |
        npm run coverage
    - name: codecov
      if: matrix.node == '12.x'
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/clover.xml
        flags: unittests
        name: codecov-umbrella    
    - name: git push release
      if: matrix.node == '12.x'
      run: |
        git checkout -b release
        git remote set-url origin https://TakenokoTech:${{ secrets.GITHUB_TOKEN }}@github.com/nokotech/actions.git
        git push --set-upstream origin release
